---
abstract: 'JSON module for JS'
author:
  - 'Stevan Little is the packager of JS-JSON'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: 'Public Domain'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: JS::JSON
name: JS-JSON
no_index:
  directory:
    - inc
    - t
requires:
  JS: 0.17
  perl: 5.6.0
version: 0.02
